### ISSUE TITLE
Is this an attempt to force everybody to implement the controversial Manifest V3?

### ISSUE THREAD

**Issue by alexolog** [w3c/webextensions#5]
Is this an attempt to force everybody to implement the controversial Manifest V3 and kill off ad blockers such as uBlock Origin?

**Comment by jaylinski** [comment]
No. Source: https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/

**Comment by alexolog** [comment]
Thank you

**Comment by Jack-Works** [comment]
Maybe out of topic. I investigate Manifest V3 support in our extension and found the Chrome implementation has many bugs/un-features that block us.

**Comment by dotproto** [comment]
@Jack-Works, that is off topic ;) I'd encourage you to [create bugs](https://bugs.chromium.org/p/chromium/issues/entry) on the Chromium issue tracker or discuss the issues you're encountering on either the [chromium-extensions](https://groups.google.com/a/chromium.org/forum/#!forum/chromium-extensions) group or on [Stack Overflow](http://stackoverflow.com/questions/tagged/google-chrome-extension).

**Comment by Jack-Works** [comment]
> @Jack-Works, that is off topic ;) I'd encourage you to create bugs on the Chromium issue tracker or discuss the issues you're encountering on either the chromium-extensions group or on Stack Overflow.

Yeah, I did. But after one year there is no progress on those issues I had.

**Comment by noloader** [comment]
Based on my reading of the W3C's [Design Principals](https://www.w3.org/TR/design-principles/) and Manifest v3 design goals, Manifest v3 is not consistent with the W3C. The conflict arises because the W3C puts the user first as stated in Priorities of Constituencies. However, Manifest v3 puts the website operator and website first.

Manifest v3 should be categorically rejected by the W3C.

If Google wishes to privately pursue its agenda, then that is Ok. Organizations are welcomed to side-load a modified browser that implements Manifest v3. Organizations are free to do what they want.
